version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
    ports:
    - "27018:27017"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
